### ISSUE TITLE
Registration: Teacher Selection Error

### ISSUE THREAD

**Issue by Tyler8oliver** [ProjectCollaboTeam/Collab#1]
On new registration, during teacher selection process, there appears to be a SQL format error.

**Comment by Tyler8oliver** [comment]
```SELECT id AS id FROM user WHERE school_id = 23 AND level = 1 AND firstname'Clint' AND lastname = 'Rogers'
{ [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Clint' AND lastname = 'Rogers'' at line 1]
  stack: 'Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'Clint\' AND lastname = \'Rogers\'\' at line 1\n    at Query.Sequence._packetToError (/var/www/Collabo/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)\n    at Query.ErrorPacket (/var/www/Collabo/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)\n    at Protocol._parsePacket (/var/www/Collabo/node_modules/mysql/lib/protocol/Protocol.js:271:23)\n    at Parser.write (/var/www/Collabo/node_modules/mysql/lib/protocol/Parser.js:77:12)\n    at Protocol.write (/var/www/Collabo/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/var/www/Collabo/node_modules/mysql/lib/Connection.js:82:28)\n    at Socket.emit (events.js:107:17)\n    at readableAddChunk (_stream_readable.js:161:16)\n    at Socket.Readable.push (_stream_readable.js:125:10)\n    at TCP.onread (net.js:514:20)\n    --------------------\n    at Protocol._enqueue (/var/www/Collabo/node_modules/mysql/lib/protocol/Protocol.js:135:48)\n    at Connection.query (/var/www/Collabo/node_modules/mysql/lib/Connection.js:185:25)\n    at exports.post.professor (/var/www/Collabo/routes/index.js:446:32)\n    at Layer.handle [as handle_request] (/var/www/Collabo/node_modules/express/lib/router/layer.js:82:5)\n    at next (/var/www/Collabo/node_modules/express/lib/router/route.js:100:13)\n    at Route.dispatch (/var/www/Collabo/node_modules/express/lib/router/route.js:81:3)\n    at Layer.handle [as handle_request] (/var/www/Collabo/node_modules/express/lib/router/layer.js:82:5)\n    at /var/www/Collabo/node_modules/express/lib/router/index.js:235:24\n    at param (/var/www/Collabo/node_modules/express/lib/router/index.js:332:14)\n    at param (/var/www/Collabo/node_modules/express/lib/router/index.js:348:14)',
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
```
